import { initializeApp } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import { getFirestore, collection, doc, onSnapshot, query, orderBy, setDoc, serverTimestamp, runTransaction, getDocs } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import { getAuth, onAuthStateChanged, signInWithPopup, signOut, GoogleAuthProvider } from "https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import { firebaseConfig } from "./firebase-config.js";
const app=initializeApp(firebaseConfig),db=getFirestore(app),auth=getAuth(app),$=id=>document.getElementById(id),provider=new GoogleAuthProvider();
const DAY=86400000, TZ="Asia/Ho_Chi_Minh";
let tabs=[],homework=[],progress={},profile=null,user=null,active="all",search="",siteSettings={noHomeworkNoticeEnabled:true,oldHomeworkNoticeEnabled:true,noHomeworkNoticeTitle:"📚 Hôm nay không có bài tập mới",noHomeworkNoticeMessage:"Hôm nay chưa có bài tập mới được cập nhật.",oldHomeworkNoticeTitle:"📢 Bài tập chưa có cập nhật",oldHomeworkNoticeMessage:"Danh sách bài tập hôm nay vẫn giống ngày trước."};
let unsubs=[]; let globalUnsubs=[]; let directNotice=null, presenceTimer=null, onlineUnsub=null, gateTimer=null; let localPrefs={theme:localStorage.getItem("hh_theme")||"dark",accent:localStorage.getItem("hh_accent")||"purple",background:localStorage.getItem("hh_bg")||"default",petEnabled:localStorage.getItem("hh_pet_enabled")!=="0"};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const dayKey=d=>new Intl.DateTimeFormat("en-CA",{timeZone:TZ}).format(d||new Date());
const parseDate=v=>v?.toDate?v.toDate():v?.seconds?new Date(v.seconds*1000):v?new Date(v):null;
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const levelFromXP=xp=>Math.max(1,Math.floor(Math.sqrt(Math.max(0,xp)/100))+1);
const levelBounds=l=>({cur:(l<=1?0:(l-1)**2*100),next:l**2*100});
function applyPrefs(){document.body.classList.toggle("light",localPrefs.theme==="light"||(localPrefs.theme==="system"&&matchMedia("(prefers-color-scheme:light)").matches));document.documentElement.dataset.accent=localPrefs.accent;document.documentElement.dataset.background=localPrefs.background;$('floatingPet')?.classList.toggle('hidden',!user||!localPrefs.petEnabled);}

function hideLoginGate(){const g=$("loginGate");if(g){g.hidden=true;clearInterval(gateTimer)}}
function showLoginGate(){const g=$("loginGate");if(!g||user)return;g.hidden=false;let left=5;const timer=$("gateTimer"),close=$("gateClose");if(close)close.hidden=true;if(timer)timer.textContent="Có thể đóng sau 5 giây...";clearInterval(gateTimer);gateTimer=setInterval(()=>{left--;if(left<=0){clearInterval(gateTimer);if(close)close.hidden=false;if(timer)timer.textContent=""}else if(timer)timer.textContent=`Có thể đóng sau ${left} giây...`},1000);$("gateLogin")?.addEventListener("click",()=>signInWithPopup(auth,provider).catch(e=>alert(e.message)),{once:false});$("gateClose")?.addEventListener("click",()=>g.hidden=true,{once:true})}
function setupPresence(){if(onlineUnsub){onlineUnsub();onlineUnsub=null}if(!user)return;const ref=doc(db,"presence",user.uid);const ping=()=>setDoc(ref,{uid:user.uid,email:user.email||"",displayName:user.displayName||user.email||"Bạn",photoURL:user.photoURL||"",onlineUntil:Date.now()+90000,updatedAt:serverTimestamp()},{merge:true}).catch(()=>{});ping();clearInterval(presenceTimer);presenceTimer=setInterval(ping,30000);window.addEventListener("beforeunload",()=>setDoc(ref,{onlineUntil:0},{merge:true}).catch(()=>{}),{once:true});}
function setupOnlineList(){if(onlineUnsub){onlineUnsub();onlineUnsub=null}const c=$("onlineList");if(!c)return;onlineUnsub=onSnapshot(collection(db,"presence"),snap=>{const now=Date.now(),arr=snap.docs.map(d=>d.data()).filter(x=>x.onlineUntil>now).sort((a,b)=>String(a.displayName||a.email).localeCompare(String(b.displayName||b.email)));$("onlineCount").textContent=String(arr.length);c.innerHTML=arr.length?arr.map(x=>`<div class="online-user"><span class="online-dot"></span><img src="${esc(x.photoURL||"")}" onerror="this.style.display='none'"><div><b>${esc(x.displayName||x.email||"Bạn")}</b><small>${esc(x.email||"")}</small></div></div>`).join(""):"<span class='muted'>Chưa có ai đang online.</span>"});}
function showDirectNotice(d,force=false){const o=$("directNoticeOverlay");if(!o||!d?.message)return;const id=String(d.id||d.sentAt?.seconds||d.updatedAt?.seconds||"");if(!force&&localStorage.getItem("hh_notice_done")===id)return;directNotice={...d,id};$("directNoticeTitle").textContent=d.title||"Thông báo trực tiếp";$("directNoticeMessage").textContent=d.message;o.hidden=false;}
function setupDirectNotice(){onSnapshot(doc(db,"settings","directNotification"),snap=>{if(!snap.exists())return;const d=snap.data();showDirectNotice(d);});$("directNoticeX")?.addEventListener("click",()=>$("directNoticeOverlay").hidden=true);$("directNoticeNoReplay")?.addEventListener("click",()=>{if(directNotice?.id)localStorage.setItem("hh_notice_done",directNotice.id);$("directNoticeOverlay").hidden=true});$("directNoticeLater")?.addEventListener("click",()=>{const d=directNotice;$("directNoticeOverlay").hidden=true;if(d?.id){localStorage.setItem("hh_notice_done",d.id);setTimeout(()=>{if(!user) return;localStorage.removeItem("hh_notice_done");showDirectNotice(d,true)},10*60*1000)}});}
function renderAuth(){const area=$("userArea");if(!user){showLoginGate();area.innerHTML='<button id="googleLogin" class="google-mini">G&nbsp; Đăng nhập Google</button>';$('googleLogin').onclick=()=>signInWithPopup(auth,provider).catch(console.error);$('greeting').textContent="Đăng nhập để lưu tiến độ, Streak, XP và Pet trên mọi thiết bị.";return}hideLoginGate();setupPresence();const name=user.displayName||user.email||"Bạn";area.innerHTML=`<div class="user-pill"><img class="avatar-img" src="${esc(user.photoURL||"")}" onerror="this.style.display='none';this.nextElementSibling.style.display='grid'"><span class="avatar" style="display:none">${esc((name[0]||"U").toUpperCase())}</span><div><b>${esc(name)}</b><small>🔥 <span id="userStreak">${num(profile?.streak)}</span> ngày</small></div><button id="logoutGoogle" class="logout-mini">Thoát</button></div>`;const img=area.querySelector('.avatar-img');if(img?.src)img.onload=()=>area.querySelector('.avatar').style.display='none';$('logoutGoogle').onclick=()=>signOut(auth);$('greeting').textContent=`Chào ${name} 👋 Hôm nay mình làm bài nhé!`}
function ensureProfile(u){return runTransaction(db,async tx=>{const ref=doc(db,"users",u.uid),snap=await tx.get(ref),d=snap.exists()?snap.data():{},today=dayKey(),last=d.lastVisitDate||"";let streak=Math.max(0,num(d.currentStreak??d.streak));let longest=Math.max(streak,num(d.longestStreak));let xp=Math.max(0,num(d.totalXP));let points=Math.max(0,num(d.points));if(last!==today){const prev=last?new Date(last+"T12:00:00+07:00"):null,cur=new Date(today+"T12:00:00+07:00"),gap=prev?Math.round((cur-prev)/DAY):0;streak=last&&gap===1?streak+1:1;longest=Math.max(longest,streak);xp+=20;points+=10;tx.set(ref,{uid:u.uid,email:u.email||d.email||"",displayName:u.displayName||d.displayName||u.email||"Bạn",photoURL:u.photoURL||d.photoURL||"",streak,currentStreak:streak,longestStreak:longest,highestStreak:longest,totalXP:xp,points,level:levelFromXP(xp),lastVisitDate:today,lastVisitAt:serverTimestamp(),lastLoginAt:serverTimestamp(),updatedAt:serverTimestamp(),pet:{type:d.pet?.type||"flamey",skin:d.pet?.skin||"default",position:d.pet?.position||{x:82,y:70}},unlockedItems:Array.isArray(d.unlockedItems)?d.unlockedItems:[],equippedItems:Array.isArray(d.equippedItems)?d.equippedItems:[]},{merge:true});}else tx.set(ref,{email:u.email||d.email||"",displayName:u.displayName||d.displayName||u.email||"Bạn",photoURL:u.photoURL||d.photoURL||"",lastLoginAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});});}
async function award(uid,deltaXP=0,deltaPoints=0,reason="reward"){const ref=doc(db,"users",uid);await runTransaction(db,async tx=>{const s=await tx.get(ref),d=s.exists()?s.data():{};const xp=Math.max(0,num(d.totalXP)+deltaXP),points=Math.max(0,num(d.points)+deltaPoints);tx.set(ref,{totalXP:xp,points,level:levelFromXP(xp),lastRewardReason:reason,lastRewardAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});});}
async function completeHomework(id,checked){
 if(!user)return signInWithPopup(auth,provider);
 const progressRef=doc(db,"users",user.uid,"homeworkProgress",id), userRef=doc(db,"users",user.uid);
 const xpPer=Math.max(0,num(siteSettings.xpPerHomework,30)), pointsPer=Math.max(0,num(siteSettings.pointsPerHomework,20));
 if(!checked){
   await runTransaction(db,async tx=>{
     const ps=await tx.get(progressRef), us=await tx.get(userRef);
     if(!ps.exists()||!ps.data().completed)return;
     const d=us.exists()?us.data():{},xp=Math.max(0,num(d.totalXP)-num(ps.data().xp,xpPer)),points=Math.max(0,num(d.points)-num(ps.data().points,pointsPer));
     tx.set(progressRef,{completed:false,updatedAt:serverTimestamp()},{merge:true});
     tx.set(userRef,{totalXP:xp,points,level:levelFromXP(xp),completedHomeworkCount:Math.max(0,num(d.completedHomeworkCount)-1),updatedAt:serverTimestamp()},{merge:true});
   });
   return;
 }
 if(progress[id]?.completed)return;
 const today=dayKey(),todays=homework.filter(h=>dayKey(parseDate(h.createdAt))===today),dailyEligible=todays.length>0&&todays.every(h=>progress[h.id]?.completed||h.id===id);
 await runTransaction(db,async tx=>{
   const ps=await tx.get(progressRef),us=await tx.get(userRef);
   if(ps.exists()&&ps.data().completed)return;
   const d=us.exists()?us.data():{},oldDaily=d.dailyRewardDate||"",dailyBonus=dailyEligible&&oldDaily!==today?100:0,dailyPoints=dailyEligible&&oldDaily!==today?50:0;
   const xp=Math.max(0,num(d.totalXP)+xpPer+dailyBonus),points=Math.max(0,num(d.points)+pointsPer+dailyPoints);
   tx.set(progressRef,{completed:true,completedAt:serverTimestamp(),xp:xpPer,points:pointsPer},{merge:true});
   tx.set(userRef,{totalXP:xp,points,level:levelFromXP(xp),completedHomeworkCount:num(d.completedHomeworkCount)+1,...(dailyBonus?{dailyRewardDate:today}:{ }),updatedAt:serverTimestamp()},{merge:true});
 });
 showToast(dailyEligible?`🎉 Hoàn thành toàn bộ hôm nay! +${xpPer+100} XP · +${pointsPer+50} Points`:`✨ +${xpPer} XP · +${pointsPer} Points`);
}

function renderStats(){const streak=Math.max(0,num(profile?.currentStreak??profile?.streak));const xp=Math.max(0,num(profile?.totalXP)),points=Math.max(0,num(profile?.points)),level=Math.max(1,num(profile?.level,levelFromXP(xp))),b=levelBounds(level),pct=Math.min(100,Math.max(0,(xp-b.cur)/(b.next-b.cur)*100));$('heroStreak').textContent=user?streak:"—";$('heroLevel').textContent=user?`Lv.${level}`:"—";$('heroPoints').textContent=user?points.toLocaleString("vi-VN"):"—";$('xpLevelText').textContent=user?`⭐ Level ${level}`:"Đăng nhập để bắt đầu";$('xpText').textContent=user?`${xp.toLocaleString("vi-VN")} / ${b.next.toLocaleString("vi-VN")} XP · còn ${Math.max(0,b.next-xp).toLocaleString("vi-VN")} XP lên level`:"XP và tiến độ sẽ được lưu bằng Firebase";$('xpPercent').textContent=user?`${Math.round(pct)}%`:"0%";$('xpBar').style.width=`${user?pct:0}%`;const today=dayKey(),todays=homework.filter(h=>dayKey(parseDate(h.createdAt))===today),done=todays.filter(h=>progress[h.id]?.completed).length;$('dailyProgress').textContent=`☑ ${done} / ${todays.length} bài hôm nay`;if($('userStreak'))$('userStreak').textContent=String(streak);applyPrefs();}
function renderTabs(){
 $('tabs').innerHTML=`<button class="tab ${active==='all'?'active':''}" data-tab="all">✨ Tất cả</button>`+tabs.map(t=>`<button class="tab ${active===t.id?'active':''}" data-tab="${esc(t.id)}">${esc(t.icon||'📚')} ${esc(t.name)}</button>`).join('');document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{active=b.dataset.tab;renderTabs();render()});}
function safeLinks(h){const raw=Array.isArray(h.links)?h.links:(h.url?[h.url]:[]);return raw.map(x=>String(x||"").trim()).filter(x=>{try{const u=new URL(x);return u.protocol==="http:"||u.protocol==="https:";}catch{return false;}}).slice(0,10);}
function render(){const c=$("homeworkList"),empty=$("empty");let list=homework.filter(h=>{const tab=active==="all"||h.subjectId===active;const q=!search||`${h.title||""} ${h.content||""} ${h.url||""} ${(h.links||[]).join(" ")}`.toLowerCase().includes(search);return tab&&q});list.sort((a,b)=>{const p=Number(!!b.pinned)-Number(!!a.pinned);return p||((parseDate(b.createdAt)?.getTime()||0)-(parseDate(a.createdAt)?.getTime()||0));});empty.classList.toggle("hidden",list.length>0);c.innerHTML=list.map((h,i)=>{const t=tabs.find(x=>x.id===h.subjectId),done=!!progress[h.id]?.completed,due=parseDate(h.dueDate),over=due&&due<new Date(),links=safeLinks(h);return `<article class="card ${h.pinned?"pinned":""} ${done?"completed":""}" style="animation-delay:${Math.min(i,10)*35}ms"><div class="card-top"><span class="subject">${esc(t?.icon||"📚")} ${esc(t?.name||"Chưa phân loại")}</span><span class="badge ${over?"red":""}">${h.pinned?"📌 Ghim":h.important?"⭐ Quan trọng":"Mới"}</span></div><h2>${esc(h.title)}</h2><div class="content">${esc(h.content)}</div>${due?`<div class="due ${over?"red":""}">⏰ Hạn: ${due.toLocaleString("vi-VN",{dateStyle:"medium",timeStyle:"short"})} · ${over?"Đã hết hạn":"Còn hạn"}</div>`:""}${links.length?`<div class="homework-links">${links.map((url,n)=>`<div class="link-actions"><a class="primary small" href="${esc(url)}" target="_blank" rel="noopener noreferrer">🔗 Mở link ${n+1}</a><button class="ghost small" type="button" data-preview-url="${esc(url)}">👁 Xem trước</button><a class="ghost small" href="${esc(url)}" target="_blank" rel="noopener noreferrer" download>⬇ Download</a></div>`).join("")}</div>`:""}<div class="card-footer"><label class="task-check"><input type="checkbox" data-homework="${esc(h.id)}" ${done?"checked":""}><span></span><b>${done?"Đã hoàn thành":"Đã làm"}</b></label><span class="xp-chip">⭐ +${Math.max(0,num(siteSettings.xpPerHomework,30))} XP</span></div></article>`}).join("");document.querySelectorAll("[data-homework]").forEach(c=>c.onchange=e=>completeHomework(e.target.dataset.homework,e.target.checked));document.querySelectorAll("[data-preview-url]").forEach(b=>b.onclick=()=>previewLink(b.dataset.previewUrl));$("status").textContent=`${list.length} bài tập`;renderStats();}
function previewLink(url){let d=$("linkPreviewDialog");if(!d){d=document.createElement("dialog");d.id="linkPreviewDialog";d.innerHTML='<div class="modal modal-wide"><div class="panel-title"><h2>👁 Xem trước</h2><button class="icon-btn" id="closeLinkPreview">×</button></div><iframe id="linkPreviewFrame" title="Xem trước link" style="width:100%;height:65vh;border:0;border-radius:12px;background:#fff"></iframe><p class="muted">Nếu website không cho nhúng, hãy dùng nút mở tab mới.</p></div>';document.body.appendChild(d);$("closeLinkPreview").onclick=()=>d.close();}$("linkPreviewFrame").src=url;d.showModal();}
function showToast(text){const x=document.createElement('div');x.className='toast';x.textContent=text;document.body.appendChild(x);setTimeout(()=>x.classList.add('show'),20);setTimeout(()=>{x.classList.remove('show');setTimeout(()=>x.remove(),250)},2600);}
function openProfile(){if(!user)return signInWithPopup(auth,provider);const p=profile||{},streak=num(p.streak),longest=num(p.longestStreak),xp=num(p.totalXP),level=num(p.level,levelFromXP(xp)),done=Object.values(progress).filter(x=>x.completed).length;$("profileContent").innerHTML=`<div class="panel-title"><div><p class="eyebrow">YOUR PROGRESS</p><h2>👤 Hồ sơ</h2></div><button class="icon-btn" id="closeProfile">×</button></div><div class="profile-hero"><img src="${esc(user.photoURL||'')}" class="profile-avatar" onerror="this.style.display='none'"><div><h2>${esc(user.displayName||user.email||'Bạn')}</h2><p class="muted">${esc(user.email||'')}</p></div></div><div class="profile-stats"><div>🔥<b>${streak}</b><small>Streak</small></div><div>🏆<b>${longest}</b><small>Cao nhất</small></div><div>⭐<b>${xp}</b><small>XP</small></div><div>💎<b>${num(p.points)}</b><small>Points</small></div></div><div class="achievement-list"><h3>🏆 Thành tựu</h3>${achievementRows(p,done)}</div>`;$("profileDialog").showModal();$('closeProfile').onclick=()=>$("profileDialog").close();}
function achievementRows(p,done){const s=num(p.streak),xp=num(p.totalXP);return [['🔥 First Flame',s>=1,'Đăng nhập ngày đầu tiên'],['🔥 Week Warrior',s>=7,'7 ngày liên tục'],['🔥 Two Weeks',s>=14,'14 ngày liên tục'],['📚 Homework Hero',done>=50,`${done}/50 bài hoàn thành`],['⚡ XP Hunter',xp>=1000,'Đạt 1.000 XP'],['👑 Legend',s>=100,'100 ngày liên tục']].map(a=>`<div class="achievement ${a[1]?'unlocked':''}"><span>${a[1]?'✓':'🔒'}</span><div><b>${a[0]}</b><small>${a[2]}</small></div></div>`).join('')}
function petCatalog(){return [
 {id:'default',emoji:'🔥',name:'Flamey',type:'skin',unlock:1,desc:'Ngọn lửa đầu tiên luôn ở bên bạn.',mood:'•ᴗ•'},
 {id:'cap',emoji:'🔥',name:'School Cap',type:'hat',unlock:7,accessory:'🧢',desc:'Mũ học sinh dành cho chiến binh 7 ngày.',mood:'⌐■ᴗ■'},
 {id:'hoodie',emoji:'🔥',name:'Hoodie',type:'outfit',unlock:14,accessory:'👕',desc:'Áo hoodie siêu ấm áp.',mood:'ᵔᴗᵔ'},
 {id:'glasses',emoji:'🔥',name:'Smart Glasses',type:'glasses',unlock:21,accessory:'👓',desc:'Flamey trở thành học bá.',mood:'⌐ᴗ⌐'},
 {id:'crown',emoji:'🔥',name:'Crown',type:'crown',unlock:30,accessory:'👑',desc:'Phần thưởng cho chuỗi cực bền.',mood:'^ᴗ^'},
 {id:'galaxy',emoji:'🌌',name:'Galaxy Flame',type:'skin',unlock:75,desc:'Phiên bản hiếm với năng lượng vũ trụ.',mood:'✦ᴗ✦'}
]}
function petVisual(pet){const skin=pet?.skin||'default',item=petCatalog().find(x=>x.id===skin)||petCatalog()[0];return `<div class="pet-orbit"><div class="pet-glow"></div><div class="pet-character ${esc(skin)}"><span class="pet-emoji">${item.emoji}</span>${item.accessory?`<span class="pet-accessory">${item.accessory}</span>`:''}<span class="pet-eyes">${item.mood}</span><span class="pet-spark s1">✦</span><span class="pet-spark s2">✧</span></div></div>`}
function petMood(streak){if(streak>=30)return ['👑','Flamey đang cực kỳ tự hào!','Bạn là huyền thoại rồi.'];if(streak>=7)return ['😎','Flamey đang rất sung!','Giữ chuỗi tiếp nhé!'];if(streak>=1)return ['😊','Flamey đang vui!','Làm thêm một bài để Flamey lớn hơn.'];return ['😴','Flamey đang chờ bạn...','Đăng nhập và bắt đầu chuỗi nhé.']}
function openPet(){if(!user)return signInWithPopup(auth,provider);const p=profile||{},s=num(p.streak),skin=p.pet?.skin||'default',catalog=petCatalog(),m=petMood(s);const unlocked=x=>s>=x.unlock||(Array.isArray(p.unlockedItems)&&p.unlockedItems.includes(x.id));$('petContent').innerHTML=`<div class="panel-title"><div><p class="eyebrow">PET HOME</p><h2>🐾 Góc của Flamey</h2><p class="muted">Không chỉ là tủ đồ — đây là nơi Flamey sống, vui chơi và đồng hành với bạn.</p></div><button class="icon-btn" id="closePet" aria-label="Đóng">×</button></div><div class="pet-dashboard"><div class="pet-showcase pet-home-card"><div class="pet-stage">${petVisual(p.pet)}</div><div class="pet-info"><div class="pet-status"><span>${m[0]} ${m[1]}</span><span class="pet-level">Lv.${num(p.level,1)}</span></div><h2>🔥 Flamey</h2><p class="muted">${m[2]}</p><div class="pet-bars"><div><span>❤️ Thân thiết</span><b>${Math.min(100,20+s)}%</b><i><em style="width:${Math.min(100,20+s)}%"></em></i></div><div><span>⚡ Năng lượng</span><b>${Math.min(100,60+(s%30))}%</b><i><em style="width:${Math.min(100,60+(s%30))}%"></em></i></div></div><div class="pet-actions"><button id="petPlay" class="primary">🎮 Chơi với Flamey</button><button id="petFeed" class="ghost">🍪 Cho ăn</button></div></div></div><div class="pet-wardrobe"><div class="wardrobe-head"><div><h3>👕 Trang bị</h3><p class="muted">Mở khóa bằng Streak rồi bấm vào món đồ để trang bị.</p></div><span>${catalog.filter(unlocked).length}/${catalog.length} đã mở</span></div><div class="pet-grid">${catalog.map(x=>{const ok=unlocked(x),eq=skin===x.id;return `<button type="button" class="pet-item ${eq?'equipped':''} ${ok?'':'locked'}" data-skin="${x.id}" ${ok?'':'disabled'}><span class="pet-item-icon">${x.emoji}</span>${x.accessory?`<span class="pet-item-acc">${x.accessory}</span>`:''}<b>${x.name}</b><small>${eq?'✓ Đang trang bị':ok?'✓ Đã mở':'🔒 Streak '+x.unlock}</small></button>`}).join('')}</div></div></div>`;$('petDialog').showModal();$('closePet').onclick=()=>$('petDialog').close();document.querySelectorAll('[data-skin]').forEach(b=>b.onclick=async()=>{const next=b.dataset.skin;try{await setDoc(doc(db,'users',user.uid),{pet:{...(profile?.pet||{}),type:'flamey',skin:next},equippedItems:[next],updatedAt:serverTimestamp()},{merge:true});showToast(`🐾 Đã trang bị ${catalog.find(x=>x.id===next)?.name||'món đồ'} cho Flamey!`);openPet();}catch(e){console.error(e);showToast('❌ Không thể lưu trang bị, thử lại nhé.')}});$('petPlay').onclick=()=>{const stage=document.querySelector('.pet-stage');stage?.classList.remove('pet-happy');void stage?.offsetWidth;stage?.classList.add('pet-happy');showToast('🎮 Flamey: Yay! Chơi nữa đi!')};$('petFeed').onclick=()=>{showToast('🍪 Flamey: Ngon quá! ❤️');const stage=document.querySelector('.pet-stage');stage?.classList.add('pet-happy');setTimeout(()=>stage?.classList.remove('pet-happy'),800)};}

function showUpdateNotice(){const dismissed=localStorage.getItem('hh_notice_dismissed'),today=dayKey();if(dismissed===today)return;const latest=homework.reduce((m,h)=>{const d=parseDate(h.createdAt);return d&&(!m||d>m)?d:m},null);let title='',text='';if(!homework.length){if(siteSettings.noHomeworkNoticeEnabled===false)return;title=siteSettings.noHomeworkNoticeTitle;text=siteSettings.noHomeworkNoticeMessage}else{if(!latest)return;const latestKey=dayKey(latest);if(latestKey===today)return;if(siteSettings.oldHomeworkNoticeEnabled===false)return;const diff=Math.max(1,Math.round((new Date(today+'T12:00:00+07:00')-new Date(latestKey+'T12:00:00+07:00'))/DAY));title=siteSettings.oldHomeworkNoticeTitle;text=(siteSettings.oldHomeworkNoticeMessage||'').replaceAll('{days}',String(diff)).replaceAll('{date}',latest.toLocaleDateString('vi-VN'));}$('noticeTitle').textContent=title;$('noticeText').textContent=text;$('updateNotice').classList.remove('hidden')}
$('noticeClose').onclick=()=>{$('updateNotice').classList.add('hidden');localStorage.setItem('hh_notice_dismissed',dayKey())};$('search').oninput=e=>{search=e.target.value.toLowerCase();$('clearSearch').classList.toggle('hidden',!search);render()};$('clearSearch').onclick=()=>{$('search').value='';search='';$('clearSearch').classList.add('hidden');render()};$('themeBtn').onclick=()=>{localPrefs.theme=document.body.classList.contains('light')?'dark':'light';localStorage.setItem('hh_theme',localPrefs.theme);applyPrefs()};$('settingsBtn').onclick=()=>{$('settingsDialog').showModal();$('petEnabled').checked=localPrefs.petEnabled};$('closeSettings').onclick=()=>$('settingsDialog').close();$('saveSettings').onclick=()=>{localPrefs.petEnabled=$('petEnabled').checked;localStorage.setItem('hh_pet_enabled',localPrefs.petEnabled?'1':'0');$('settingsDialog').close();applyPrefs()};document.querySelectorAll('[data-theme]').forEach(b=>b.onclick=()=>{localPrefs.theme=b.dataset.theme;localStorage.setItem('hh_theme',localPrefs.theme);applyPrefs()});document.querySelectorAll('[data-accent]').forEach(b=>b.onclick=()=>{localPrefs.accent=b.dataset.accent;localStorage.setItem('hh_accent',localPrefs.accent);applyPrefs()});document.querySelectorAll('[data-bg]').forEach(b=>b.onclick=()=>{localPrefs.background=b.dataset.bg;localStorage.setItem('hh_bg',localPrefs.background);applyPrefs()});$('profileNav').onclick=openProfile;$('petNav').onclick=openPet;$('petNav').onclick=openPet;document.querySelectorAll('[data-main-nav]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-main-nav]').forEach(x=>x.classList.remove('active'));b.classList.add('active');const n=b.dataset.mainNav;if(n==='home')window.scrollTo({top:0,behavior:'smooth'});if(n==='homework')$('homeworkSection').scrollIntoView({behavior:'smooth',block:'start'});if(n==='pet')openPet();if(n==='profile')openProfile();if(n==='schedule')window.location.href='schedule.html';});
const pet=$('floatingPet');
let dragging=false,dragMoved=false,ox=0,oy=0;
function setPetPos(x,y,save=true){
  if(!pet || !Number.isFinite(x) || !Number.isFinite(y)) return;
  x=Math.max(3,Math.min(97,x)); y=Math.max(6,Math.min(90,y));
  pet.style.left=x+"%"; pet.style.top=y+"%";
  if(save && user) setDoc(doc(db,"users",user.uid),{pet:{...(profile?.pet||{}),position:{x,y}},updatedAt:serverTimestamp()},{merge:true}).catch(e=>console.warn("Pet position:",e));
}
function loadPet(){const pos=profile?.pet?.position;setPetPos(num(pos?.x,82),num(pos?.y,70),false);}
if(pet){
  pet.addEventListener("pointerdown",e=>{e.preventDefault();dragging=true;dragMoved=false;try{pet.setPointerCapture(e.pointerId)}catch(_){ }const r=pet.getBoundingClientRect();ox=e.clientX-r.left;oy=e.clientY-r.top;pet.classList.add("dragging");});
  pet.addEventListener("pointermove",e=>{if(!dragging)return;const x=(e.clientX-ox)/Math.max(1,innerWidth)*100,y=(e.clientY-oy)/Math.max(1,innerHeight)*100;if(Math.abs(x-parseFloat(pet.style.left||"82"))>0.4||Math.abs(y-parseFloat(pet.style.top||"70"))>0.4)dragMoved=true;setPetPos(x,y,false);});
  const finishDrag=e=>{if(!dragging)return;dragging=false;pet.classList.remove("dragging");if(dragMoved)setPetPos(parseFloat(pet.style.left),parseFloat(pet.style.top),true);try{pet.releasePointerCapture(e.pointerId)}catch(_){ }};
  pet.addEventListener("pointerup",finishDrag);pet.addEventListener("pointercancel",finishDrag);
  pet.addEventListener("click",e=>{if(dragMoved){e.preventDefault();e.stopPropagation();dragMoved=false;return;}pet.classList.remove("pet-play");void pet.offsetWidth;pet.classList.add("pet-play");showToast(profile?.streak>=7?"🔥 Flamey: Giữ chuỗi thôi!":"🔥 Flamey: Đi làm bài nào!");});
}
function cleanup(){unsubs.forEach(u=>u&&u());unsubs=[];progress={};profile=null}
setupOnlineList();setupDirectNotice();
onAuthStateChanged(auth,async u=>{cleanup();user=u;renderAuth();renderStats();if(!u)return;try{await ensureProfile(u)}catch(e){console.error(e)}unsubs.push(onSnapshot(doc(db,'users',u.uid),s=>{profile=s.exists()?s.data():{};renderAuth();renderStats();loadPet();}));unsubs.push(onSnapshot(collection(db,'users',u.uid,'homeworkProgress'),s=>{progress={};s.docs.forEach(d=>progress[d.id]=d.data());render();}));loadPet()});
globalUnsubs.push(onSnapshot(query(collection(db,'subjects'),orderBy('order','asc')),
 s=>{tabs=s.docs.map(d=>({id:d.id,...d.data()}));renderTabs();render()},e=>console.error(e)));
globalUnsubs.push(onSnapshot(query(collection(db,'homework'),orderBy('createdAt','desc')),s=>{homework=s.docs.map(d=>({id:d.id,...d.data()}));render();showUpdateNotice()},e=>console.error(e)));
globalUnsubs.push(onSnapshot(doc(db,'settings','site'),s=>{if(s.exists())siteSettings={...siteSettings,...s.data()};showUpdateNotice()}));
setInterval(async()=>{try{const hs=await getDocs(query(collection(db,'homework'),orderBy('createdAt','desc')));homework=hs.docs.map(d=>({id:d.id,...d.data()}));render();}catch(e){console.warn("Homework Hub refresh:",e)}},10000);
$('today').textContent=new Intl.DateTimeFormat('vi-VN',{dateStyle:'full',timeZone:TZ}).format(new Date());applyPrefs();render();
