import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";import{getAuth,onAuthStateChanged,signInWithPopup,signInWithRedirect,getRedirectResult,GoogleAuthProvider,signOut}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";import{getFirestore,collection,doc,setDoc,query,orderBy,onSnapshot,addDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";import{firebaseConfig}from"../js/firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();const $=id=>document.getElementById(id);let me=null,users=[],selected=null,userUnsub=null,msgUnsub=null,presenceTimer=null,presenceUnsub=null,signing=false;
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const avatar=(u,cls="avatar")=>`<img class="${cls}" src="${esc(u.photoURL||"")}" alt="" onerror="this.src='data:image/svg+xml,%3Csvg xmlns=%27http://www.w3.org/2000/svg%27 width=%2744%27 height=%2744%27%3E%3Crect width=%27100%25%27 height=%27100%25%27 rx=%2750%25%27 fill=%27%23242840%27/%3E%3C/svg%3E'">`;
async function login(){if(signing)return;signing=true;try{await signInWithPopup(auth,provider)}catch(e){if(e.code==="auth/popup-blocked")try{await signInWithRedirect(auth,provider)}catch(r){alert(r.message||"Không thể đăng nhập Google.")}else if(!["auth/popup-closed-by-user","auth/cancelled-popup-request"].includes(e.code))alert(e.message||"Không thể đăng nhập Google.")}finally{signing=false}}
getRedirectResult(auth).catch(e=>console.warn("Chat redirect:",e));
function chatId(a,b){return[a,b].sort().join("_")}
async function ensureChatProfile(){if(!me)return;await setDoc(doc(db,"chat_profiles",me.uid),{uid:me.uid,email:me.email||"",displayName:me.displayName||me.email||"Bạn",photoURL:me.photoURL||"",updatedAt:serverTimestamp()},{merge:true})}
async function writePresence(online=true){if(!me)return;await setDoc(doc(db,"presence",me.uid),{uid:me.uid,email:me.email||"",displayName:me.displayName||me.email||"Bạn",photoURL:me.photoURL||"",onlineUntil:online?Date.now()+90000:0,updatedAt:serverTimestamp()},{merge:true}).catch(()=>{})}
function startPresence(){if(presenceTimer)clearInterval(presenceTimer);writePresence(true);presenceTimer=setInterval(()=>writePresence(true),30000)}
function stopPresence(){if(presenceTimer)clearInterval(presenceTimer);presenceTimer=null;if(me)writePresence(false)}
function renderUsers(){const q=($('userSearch')?.value||"").trim().toLowerCase();const now=Date.now();const list=users.filter(u=>u.uid!==me?.uid).filter(u=>`${u.displayName||""} ${u.email||""}`.toLowerCase().includes(q));$('users').innerHTML=list.length?list.map(u=>`<button class="user ${selected?.uid===u.uid?'active':''}" data-uid="${esc(u.uid)}">${avatar(u)}<span class="user-main"><b>${esc(u.displayName||u.email||"Người dùng")}</b><small>${esc(u.email||"")}</small></span><span class="dot ${Number(u.onlineUntil||0)>now?'online':''}"></span></button>`).join(""):"<span class='muted'>Chưa có người dùng khác. Hãy đăng nhập tài khoản Google thứ hai vào /chat để bắt đầu chat.</span>";document.querySelectorAll('.user').forEach(b=>b.onclick=()=>openChat(users.find(u=>u.uid===b.dataset.uid)))}
function openChat(u){if(!u)return;selected=u;$('emptyChat').hidden=true;$('chatPanel').hidden=false;$('usersPanel').classList.add('chat-open');$('chatName').textContent=u.displayName||u.email||"Người dùng";$('chatStatus').textContent=Number(u.onlineUntil||0)>Date.now()?"🟢 online":"offline";$('chatAvatar').src=u.photoURL||"";if(msgUnsub)msgUnsub();const id=chatId(me.uid,u.uid),ref=collection(db,"chats",id,"messages");msgUnsub=onSnapshot(query(ref,orderBy("createdAt","asc")),snap=>{const c=$('messages');c.innerHTML=snap.docs.map(d=>{const x=d.data(),mine=x.senderId===me.uid,t=x.createdAt?.toDate?.();return`<div class="msg ${mine?'mine':''}">${esc(x.text)}${t?`<time>${t.toLocaleTimeString('vi-VN',{hour:'2-digit',minute:'2-digit'})}</time>`:""}</div>`}).join("");c.scrollTop=c.scrollHeight},e=>console.error("Chat messages:",e));renderUsers()}
$('composer').onsubmit=async e=>{e.preventDefault();const input=$('messageInput'),text=input.value.trim();if(!me||!selected||!text)return;if(text.length>2000)return alert("Tin nhắn tối đa 2000 ký tự.");input.value="";const id=chatId(me.uid,selected.uid);await setDoc(doc(db,"chats",id),{members:[me.uid,selected.uid],lastMessage:text,lastSenderId:me.uid,updatedAt:serverTimestamp()},{merge:true});await addDoc(collection(db,"chats",id,"messages"),{senderId:me.uid,receiverId:selected.uid,text,createdAt:serverTimestamp()})};$('login').onclick=login;$('googleLogin')?.addEventListener('click',login);$('logout').onclick=()=>signOut(auth);$('userSearch').oninput=renderUsers;$('backUsers').onclick=()=>{$('chatPanel').hidden=true;$('emptyChat').hidden=false;$('usersPanel').classList.remove('chat-open');selected=null;renderUsers()};
onAuthStateChanged(auth,async u=>{if(presenceUnsub){presenceUnsub();presenceUnsub=null}if(msgUnsub){msgUnsub();msgUnsub=null}stopPresence();me=u||null;if(!u){$('loginBox').hidden=false;$('me').textContent="Chưa đăng nhập";$('users').innerHTML="<span class='muted'>Đăng nhập để xem danh sách người dùng.</span>";return}$('loginBox').hidden=true;$('me').textContent=u.displayName||u.email||"Bạn";try{await ensureChatProfile();startPresence()}catch(e){console.error("Chat profile:",e)}const q=query(collection(db,"chat_profiles"),orderBy("displayName","asc"));if(userUnsub)userUnsub();userUnsub=onSnapshot(q,snap=>{users=snap.docs.map(d=>d.data());if(presenceUnsub)presenceUnsub();presenceUnsub=onSnapshot(collection(db,"presence"),ps=>{const status=new Map(ps.docs.map(d=>[d.id,d.data()]));users=users.map(x=>({...x,onlineUntil:status.get(x.uid)?.onlineUntil||0}));renderUsers()},e=>console.error("Chat presence:",e));renderUsers()},e=>{$('users').innerHTML="<span class='muted'>Không thể tải danh sách người dùng. Kiểm tra Firestore Rules.</span>";console.error("Chat profiles:",e)})});
window.addEventListener("beforeunload",()=>stopPresence());
