import{initializeApp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-app.js";
import{getAuth,onAuthStateChanged,signInWithPopup,signInWithRedirect,getRedirectResult,GoogleAuthProvider,signOut}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js";
import{getFirestore,collection,doc,setDoc,query,orderBy,onSnapshot,addDoc,serverTimestamp}from"https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js";
import{firebaseConfig}from"../js/firebase-config.js";
const app=initializeApp(firebaseConfig),auth=getAuth(app),db=getFirestore(app),provider=new GoogleAuthProvider();
const $=id=>document.getElementById(id);let me=null,users=[],selected=null,mode="people",profileUnsub=null,presenceUnsub=null,msgUnsub=null,presenceTimer=null,signing=false,sending=false,cooldownTimer=null,lastMessages=[],deferredInstall=null;
const fallback="data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='80' height='80'%3E%3Crect width='100%25' height='100%25' rx='50%25' fill='%23242840'/%3E%3Ctext x='50%25' y='55%25' text-anchor='middle' fill='%23fff' font-size='32'%3E%F0%9F%91%A4%3C/text%3E%3C/svg%3E";
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
const avatar=u=>`<img class="avatar" src="${esc(u.photoURL||fallback)}" onerror="this.src='${fallback}'" alt="">`;const chatId=(a,b)=>[a,b].sort().join("_");
function device(){const w=innerWidth,t=navigator.maxTouchPoints>0||matchMedia("(pointer:coarse)").matches;if(w<=700)return"📱 Điện thoại";if(w<=1100)return"📲 Tablet";return t?"💻 Màn hình cảm ứng":"🖥️ PC"}function updateDevice(){const d=device();$("deviceTip").textContent=`${d} · giao diện tự tối ưu`;$("toolDevice").textContent=d;document.body.classList.toggle("compact",innerWidth>=701&&innerWidth<=1000)}updateDevice();addEventListener("resize",updateDevice,{passive:true});addEventListener("orientationchange",()=>setTimeout(updateDevice,200),{passive:true});
async function login(){if(signing)return;signing=true;try{await signInWithPopup(auth,provider)}catch(e){if(e.code==="auth/popup-blocked"||e.code==="auth/popup-operation-not-supported"){try{await signInWithRedirect(auth,provider)}catch(r){console.error(r);alert("Không thể đăng nhập Google.")}}else if(!["auth/popup-closed-by-user","auth/cancelled-popup-request"].includes(e.code))alert(e.message||"Không thể đăng nhập Google.")}finally{signing=false}}
getRedirectResult(auth).catch(e=>console.warn("Chat redirect:",e));
async function ensureProfile(){if(!me)return;await setDoc(doc(db,"chat_profiles",me.uid),{uid:me.uid,email:me.email||"",displayName:me.displayName||me.email||"Bạn",photoURL:me.photoURL||"",updatedAt:serverTimestamp()},{merge:true})}
async function setPresence(online=true){if(!me)return;await setDoc(doc(db,"presence",me.uid),{uid:me.uid,onlineUntil:online?Date.now()+90000:0,updatedAt:serverTimestamp()},{merge:true}).catch(e=>console.warn("presence",e))}function startPresence(){clearInterval(presenceTimer);setPresence(true);presenceTimer=setInterval(()=>setPresence(true),30000)}function stopPresence(){clearInterval(presenceTimer);presenceTimer=null;if(me)setPresence(false)}function normalize(d){const x=d.data();return{uid:d.id,email:x.email||"",displayName:x.displayName||x.email||"Người dùng",photoURL:x.photoURL||""}}
function renderUsers(){const q=($("userSearch").value||"").trim().toLowerCase(),now=Date.now();if(mode==="group"){$("users").innerHTML=`<button class="user active" id="allGroupBtn">${avatar({})}<span class="user-main"><b>👥 Nhóm Homework Hub</b><small>${users.length+1} thành viên</small></span><span class="dot online"></span></button>`;$("allGroupBtn").onclick=openGroup;return}const list=users.filter(u=>u.uid!==me?.uid).filter(u=>`${u.displayName} ${u.email}`.toLowerCase().includes(q));$("users").innerHTML=list.length?list.map(u=>`<button class="user ${selected?.uid===u.uid?"active":""}" data-uid="${esc(u.uid)}">${avatar(u)}<span class="user-main"><b>${esc(u.displayName)}</b><small>${esc(u.email)}</small></span><span class="dot ${Number(u.onlineUntil||0)>now?"online":""}"></span></button>`).join(""):"<span class='muted'>Chưa tìm thấy thành viên khác.</span>";document.querySelectorAll(".user[data-uid]").forEach(b=>b.onclick=()=>openPrivate(users.find(u=>u.uid===b.dataset.uid)))}
function subscribeUsers(){if(profileUnsub)profileUnsub();if(presenceUnsub)presenceUnsub();profileUnsub=onSnapshot(collection(db,"chat_profiles"),snap=>{const base=snap.docs.map(normalize);users=base;renderUsers();if(presenceUnsub)presenceUnsub();presenceUnsub=onSnapshot(collection(db,"presence"),ps=>{const p=new Map(ps.docs.map(d=>[d.id,d.data()]));users=base.map(u=>({...u,onlineUntil:p.get(u.uid)?.onlineUntil||0}));renderUsers();if(selected){const s=users.find(u=>u.uid===selected.uid);if(s){selected=s;header(s.displayName,Number(s.onlineUntil||0)>Date.now()?"🟢 online":"⚪ offline",s.photoURL)}}},e=>console.warn("presence",e))},e=>{$("users").innerHTML="<span class='muted'>Không đọc được danh sách thành viên. Kiểm tra Firestore Rules.</span>";console.error("chat_profiles",e)})}
function header(name,status,photo){$("chatName").textContent=name;$("chatStatus").textContent=status;$("chatAvatar").src=photo||fallback}
async function ensurePrivateChat(u){const id=chatId(me.uid,u.uid);await setDoc(doc(db,"chats",id),{type:"private",members:[me.uid,u.uid],updatedAt:serverTimestamp()},{merge:true});return id}async function ensureGroup(){const members=[...new Set(users.map(u=>u.uid).concat(me.uid))];await setDoc(doc(db,"chats","all_members"),{type:"group",name:"Nhóm Homework Hub",members,updatedAt:serverTimestamp()},{merge:true});return members}
async function openPrivate(u){if(!me){showLogin();return}if(!u||u.uid===me.uid)return;mode="people";selected=u;$('emptyChat').hidden=true;$('chatPanel').hidden=false;$('usersPanel').classList.add('chat-open');header(u.displayName,Number(u.onlineUntil||0)>Date.now()?"🟢 online":"⚪ offline",u.photoURL);renderUsers();restoreDraft();try{listenMessages(await ensurePrivateChat(u),false)}catch(e){console.error("openPrivate",e);$("messages").innerHTML="<div class='muted'>Không thể mở chat. Kiểm tra Firestore Rules.</div>"}}
async function openGroup(){if(!me){showLogin();return}selected=null;mode="group";$('emptyChat').hidden=true;$('chatPanel').hidden=false;$('usersPanel').classList.add('chat-open');restoreDraft();try{const members=await ensureGroup();header("👥 Nhóm Homework Hub",`${members.length} thành viên`,fallback);listenMessages("all_members",true)}catch(e){console.error("openGroup",e);$("messages").innerHTML="<div class='muted'>Không thể mở nhóm chat. Kiểm tra Firestore Rules.</div>"}renderUsers()}
function renderMessage(x,isGroup,index){const mine=x.senderId===me.uid,t=x.createdAt?.toDate?.();const body=x.text?`<div>${esc(x.text)}</div>`:"";return `<div class="msg ${mine?"mine":""}" data-index="${index}">${isGroup&&!mine?`<div class="sender">${esc(x.senderName||x.senderEmail||"Thành viên")}</div>`:""}${body}${t?`<time>${t.toLocaleString("vi-VN",{hour:"2-digit",minute:"2-digit",day:"2-digit",month:"2-digit"})}</time>`:""}</div>`}
function listenMessages(id,isGroup){if(msgUnsub)msgUnsub();msgUnsub=onSnapshot(query(collection(db,"chats",id,"messages"),orderBy("createdAt","asc")),snap=>{lastMessages=snap.docs.map(d=>d.data());renderMessages(isGroup);const c=$("messages");requestAnimationFrame(()=>{c.scrollTop=c.scrollHeight})},e=>{console.error("Chat messages",e);$("messages").innerHTML="<div class='muted'>Không thể tải tin nhắn. Kiểm tra Firestore Rules.</div>"})}
function renderMessages(isGroup){const q=($("messageSearchInput")?.value||"").trim().toLowerCase();const list=q?lastMessages.filter(x=>String(x.text||"").toLowerCase().includes(q)):lastMessages;$("messages").innerHTML=list.map((x,i)=>renderMessage(x,isGroup,i)).join("")||"<div class='muted'>Chưa có tin nhắn.</div>"}
async function sendMessage(text){if(!me)return;const id=mode==="group"?"all_members":chatId(me.uid,selected.uid);const members=mode==="group"?[...new Set(users.map(u=>u.uid).concat(me.uid))]:[me.uid,selected.uid];await setDoc(doc(db,"chats",id),{type:mode==="group"?"group":"private",name:mode==="group"?"Nhóm Homework Hub":"",members,lastMessage:text,lastSenderId:me.uid,updatedAt:serverTimestamp()},{merge:true});await addDoc(collection(db,"chats",id,"messages"),{senderId:me.uid,senderName:me.displayName||me.email||"Bạn",senderEmail:me.email||"",text,createdAt:serverTimestamp()})}
function startSendCooldown(){const btn=$("sendBtn");clearInterval(cooldownTimer);sending=true;btn.disabled=true;let left=5;btn.textContent=`Gửi (${left})`;cooldownTimer=setInterval(()=>{left--;if(left<=0){clearInterval(cooldownTimer);sending=false;btn.disabled=false;btn.textContent="Gửi"}else btn.textContent=`Gửi (${left})`},1000);$("sendHint").textContent="Chờ 5 giây giữa các tin để tránh gửi dồn.";setTimeout(()=>$("sendHint").textContent="",5000)}
function draftKey(){return`hh_chat_draft_${mode}_${selected?.uid||"group"}`}function saveDraft(){localStorage.setItem(draftKey(),$("messageInput").value)}function restoreDraft(){const v=localStorage.getItem(draftKey())||"";$("messageInput").value=v;updateComposer()}
function updateComposer(){const i=$("messageInput");$("charCount").textContent=`${i.value.length}/2000`;i.style.height="auto";i.style.height=Math.min(i.scrollHeight,120)+"px";saveDraft()}
$("composer").onsubmit=async e=>{e.preventDefault();if(sending)return;const input=$("messageInput"),text=input.value.trim();if(!me){showLogin();return}if(!selected&&mode!=="group")return;if(!text)return;startSendCooldown();input.value="";updateComposer();localStorage.removeItem(draftKey());try{await sendMessage(text)}catch(e){console.error(e);input.value=text;updateComposer();alert("Không gửi được tin nhắn. Hãy thử lại sau.")}};
$("messageInput").addEventListener("input",updateComposer);$("messageInput").addEventListener("keydown",e=>{if(e.key==="Enter"&&!e.shiftKey&&!matchMedia("(max-width:700px)").matches){e.preventDefault();$("composer").requestSubmit()}});
$("emoji").onclick=()=>$("emojiBar").hidden=!$("emojiBar").hidden;$("toolEmoji").onclick=()=>{$("emojiBar").hidden=!$("emojiBar").hidden;$("messageInput").focus()};document.querySelectorAll("#emojiBar button").forEach(b=>b.onclick=()=>{const i=$("messageInput");i.value+=b.textContent;updateComposer();i.focus()});$("toolBottom").onclick=()=>{const m=$("messages");m.scrollTop=m.scrollHeight};$("toolClear").onclick=()=>{$("messageInput").value="";updateComposer();$("messageInput").focus()};$("toolTheme").onclick=()=>{document.body.classList.toggle("chat-light");localStorage.setItem("hh_chat_light",document.body.classList.contains("chat-light")?"1":"0")};if(localStorage.getItem("hh_chat_light")==="1")document.body.classList.add("chat-light");
$("chatSearchToggle").onclick=()=>{$("messageSearch").hidden=!$("messageSearch").hidden;if(!$('messageSearch').hidden){$('messageSearchInput').focus()}else renderMessages(mode==="group")};$("messageSearchInput").oninput=()=>renderMessages(mode==="group");$("messageSearchClear").onclick=()=>{$("messageSearchInput").value="";renderMessages(mode==="group")};
$("chatMore").onclick=()=>$("chatMoreMenu").hidden=!$("chatMoreMenu").hidden;$("closeMenu").onclick=()=>$("chatMoreMenu").hidden=true;$("clearDraft").onclick=()=>{$("messageInput").value="";updateComposer();$("chatMoreMenu").hidden=true};$("copyLast").onclick=async()=>{const x=lastMessages[lastMessages.length-1]?.text||"";if(x)try{await navigator.clipboard.writeText(x);$("sendHint").textContent="Đã sao chép tin nhắn cuối."}catch{alert(x)}$("chatMoreMenu").hidden=true};
$("login").onclick=login;$("emptyLogin").onclick=login;$("logout").onclick=()=>signOut(auth);$("userSearch").oninput=renderUsers;$("peopleTab").onclick=()=>{mode="people";$("peopleTab").classList.add("active");$("groupTab").classList.remove("active");renderUsers()};$("groupTab").onclick=()=>{mode="group";$("groupTab").classList.add("active");$("peopleTab").classList.remove("active");renderUsers()};$("backUsers").onclick=()=>{$("chatPanel").hidden=true;$('emptyChat').hidden=false;$('usersPanel').classList.remove('chat-open');selected=null;if(msgUnsub){msgUnsub();msgUnsub=null}renderUsers()};
function showLogin(){$("loginBox").hidden=false;$("emptyLogin").hidden=false;$("emptyChat").hidden=false;$("chatPanel").hidden=true}
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredInstall=e;$("installBtn").hidden=false});$("installBtn").onclick=async()=>{if(!deferredInstall)return;deferredInstall.prompt();await deferredInstall.userChoice;deferredInstall=null;$("installBtn").hidden=true};
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js").catch(()=>{});
onAuthStateChanged(auth,async u=>{stopPresence();me=u||null;if(msgUnsub){msgUnsub();msgUnsub=null}if(!u){if(profileUnsub)profileUnsub();if(presenceUnsub)presenceUnsub();profileUnsub=null;presenceUnsub=null;users=[];selected=null;$("loginBox").hidden=false;$("emptyLogin").hidden=false;$("logout").hidden=true;$("me").textContent="Chưa đăng nhập";$("users").innerHTML="<span class='muted'>Đăng nhập để xem danh sách thành viên Homework Hub.</span>";return}$("loginBox").hidden=true;$("emptyLogin").hidden=true;$("logout").hidden=false;$("me").textContent=u.displayName||u.email||"Bạn";try{await ensureProfile();startPresence();subscribeUsers()}catch(e){console.error("Chat init",e);$("users").innerHTML="<span class='muted'>Không thể khởi tạo chat.</span>"}});window.addEventListener("beforeunload",stopPresence);
